name: Nick Gartmann
favicon: null
layout_spectrum: 0.6600507313851267
typography_spectrum: 0.3130495394580066
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5342019300442189
  lightness: 0.43153767264448106
  saturation: 0.5663185378070921
  rhythmicContrast: 0.3887788087595254
purpose: []
